### ISSUE TITLE
Is it possible to keep all languages intact?

### ISSUE THREAD

**Issue by RetroGameTalk** [wagrenier/ZeroUndub#7]
Adding English subs removes not only French but all other languages.
We can either get English subs and break all the rest, or keep all the rest but without English subs.
Could this be solved in a future release?

**Comment by wagrenier** [comment]
No, that is why there is a warning on the inject english subtitle option. If you wish to play other languages, then don't select that option.

**Comment by RetroGameTalk** [comment]
Amazing response.

**Comment by wagrenier** [comment]
Sorry, to elaborate, in order to inject English subtitles, roughly 100kb of text needs to be injected, which overwrite most of other languages' text file, so physically it is impossible for me to do that due to the ISO9006 restrictions. For the cutscenes, how the game is setup is complicated and switching the audio is complicated as it uses a different ID method for other languages. So for that part I would say it would be possible, but I have not checked with the 50Hz/60Hz issue. Plus, I want to start going back to the second game to fix some issues and have more undub audio. If you have the skills to add for the missing languages, please do a pr and I will add you to contributors.

**Comment by RetroGameTalk** [comment]
It's alright no big deal. Sorry I can't help.
